/** ISO 3166-1 alpha-2 → ECharts world map English names */
export const ISO_TO_MAP_NAME: Record<string, string> = {
  CN: 'China',
  US: 'United States',
  JP: 'Japan',
  KR: 'Korea',
  GB: 'United Kingdom',
  DE: 'Germany',
  FR: 'France',
  CA: 'Canada',
  AU: 'Australia',
  IN: 'India',
  BR: 'Brazil',
  RU: 'Russia',
  SG: 'Singapore',
  HK: 'Hong Kong',
  TW: 'Taiwan',
  MO: 'Macao',
  TH: 'Thailand',
  VN: 'Vietnam',
  MY: 'Malaysia',
  ID: 'Indonesia',
  PH: 'Philippines',
  NL: 'Netherlands',
  IT: 'Italy',
  ES: 'Spain',
  SE: 'Sweden',
  NO: 'Norway',
  FI: 'Finland',
  DK: 'Denmark',
  CH: 'Switzerland',
  AT: 'Austria',
  BE: 'Belgium',
  PL: 'Poland',
  PT: 'Portugal',
  IE: 'Ireland',
  NZ: 'New Zealand',
  MX: 'Mexico',
  AR: 'Argentina',
  ZA: 'South Africa',
  AE: 'United Arab Emirates',
  SA: 'Saudi Arabia',
  TR: 'Turkey',
  IL: 'Israel',
  XX: 'Unknown',
};

export function countryMapName(iso: string): string {
  return ISO_TO_MAP_NAME[iso.toUpperCase()] ?? iso;
}
